services:
  banco_mysql: 
    image: mysql:8.0
    container_name: plantel_banco_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plantel_plataforma
      MYSQL_USER: plantel_usuario
      MYSQL_PASSWORD: plantel_senha
    ports:
      - "3306:3306"
    volumes:
      - dados_mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: plantel_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  dados_mysql: